name: Publish package to Maven Central Repository and create GitHub Release

on:
  push:
    tags:
      - 'v*'        # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build:
    name: Publish to Nexus and create release on GitHub
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      #- name: Release Maven package
      #  uses: samuelmeuli/action-maven-publish@v1.3.1
      #  with:
      #    gpg_private_key: ${{ secrets.PGP_KEY_PRIVATE }}
      #    gpg_passphrase: ${{ secrets.PGP_KEY_PASSPHRASE }}
      #    nexus_username: ${{ secrets.OSSRH_USERNAME }}
      #    nexus_password: ${{ secrets.OSSRH_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.commits[0].message }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        #  upload_url: ${{ steps.create_release.outputs.upload_url }}
          name: igdb-wrapper-java-${{ steps.create_release.outputs.tag_name }}
          path: target/?.jar
          if-no-files-found: warn